source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:soulmachines/SoulMachines-Specs.git'

platform :ios, '14.0'
use_frameworks!

workspace '../SMSampleProjects'
project 'SMObjectiveCSample.xcodeproj'

target 'SMObjectiveCSample' do
  pod 'JWT', '~> 2.0.0'
  pod 'SMDarwin'
  pod 'WebRTC_iOS'
  pod 'Starscream', '~> 4.0.0'
  pod 'AnyCodable-FlightSchool', '~> 0.4.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
